added feature-location and postman tests
savannavea/java-explore-with-me pull request #9
Opened 2023-10-26 10:04 UTC by savannavea

2023-10-26 19:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-10-26 19:55 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/mainService/location/mapper/LocationMapper.java
> +    public LocationResponseDto toNewLocationDto(Location location) {
А ну ка присмотрись, чем отличаются методы toNewLocationDto и toLocationResponseDto ?

2023-10-26 19:55 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/mainService/location/service/LocationServiceImpl.java
> +        List<Location> locationList = locationRepository.findAll(page).getContent();
У `Page`, который возвращает `findAll` есть метод `map` - воспользуйся им и убери лишний код.

2023-10-27 14:08 UTC, savannavea commented on main-service/src/main/java/ru/practicum/mainService/location/mapper/LocationMapper.java
> +    public LocationResponseDto toNewLocationDto(Location location) {
Исправила)))

2023-10-27 16:53 UTC, FanaticFiz approved these changes

2023-10-27 16:53 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/mainService/location/service/LocationServiceImpl.java
> +        return locationRepository
Не совсем.
Вот что я имел ввиду

```
        return locationRepository.findAll(page)
                                 .map(LocationMapper::toLocationResponseDto)
                                 .toList();
```

2023-10-29 09:49 UTC, merged